cal_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path("admin/", admin.site.urls),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("accounts/", include("allauth.urls")),
    path("", include("calendar_app.urls")),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path
from .views import (
    AboutPageView,
    ContactPageView,
    FAQPageView,
)

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactPageView.as_view(), name="contact"),
    path("faq/", FAQPageView.as_view(), name="faq"),
    # path("your-account/", YourAccountView.as_view(), name="your_account"),
]

calendar_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
import uuid
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, blank=False)

    description = models.TextField(blank=True, null=True)

    start_date = models.DateField()
    end_date = models.DateField()

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")
    organizer_alias = models.CharField(max_length=100)

    location = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)

    TYPE_CHOICES = [
        ("competition", _("competition")),
        ("workshop", _("workshop")),
        ("conference", _("conference")),
        ("show", _("show")),
        ("festival", _("festival")),
        ("convention", _("convention")),
        ("camp_intensive", _("camp/intensive")),
        ("other", _("other")),
    ]
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)

    is_aerial = models.BooleanField(default=True)

    is_verified = models.BooleanField(default=False)

    main_link = models.URLField(max_length=300)
    additional_url_1 = models.URLField(max_length=300, blank=True, null=True)
    additional_label_1 = models.CharField(max_length=100, blank=True, null=True)

    additional_url_2 = models.URLField(max_length=300, blank=True, null=True)
    additional_label_2 = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event_detail", args=[str(self.id)])

    def clean(self):
        # Ensuring the end date is not earlier than the start date
        if self.end_date < self.start_date:
            raise ValidationError(_("Start date cannot be later than end date"))

    def save(self, *args, **kwargs):
        # Calling clean() before saving to ensure validation

        self.clean()
        super().save(*args, **kwargs)

templates/calendar/calendar_layout.html
{% extends '_base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<!-- For translation -->
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>


{% include 'calendar/navigate_events.html' %}

<div id="calendar-container">
</div>



<!-- eventsModal -->
<div class="modal fade" id="eventsModal" tabindex="-1" aria-labelledby="eventsModalTitle" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="eventsModalTitle"></h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="eventsModalBody">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'Close' %}</button>
      </div>
    </div>
  </div>
</div>



<script>
    const yearsData = {{ years|safe }}
    const allEvents = {{ events|safe }}
    const eventTypes = {{ event_types|safe }}
</script>
<script src="{% static 'js/generate_calendar/main_calendar.js' %}" defer type="module"></script>


{% endblock content %}

templates/calendar/event_create.html
{% extends '_base.html' %}
{%load django_bootstrap5 %}
{% load i18n %}



{% block content %}
<form action="" method="post" id="my-form">
    {% csrf_token %}
    <h1>{% trans 'New event' %}</h1>
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissable fade show d-flex justify-content-between" role="alert" data-bs-dismiss="alert">
        {% bootstrap_form_errors form %}
        <button type="button" class="btn-close ms-2" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% bootstrap_field form.name %}
    {% bootstrap_field form.start_date %}
    {% bootstrap_field form.end_date %}
    {% bootstrap_field form.description %}
    {% bootstrap_field form.location %}
    <label><input type="checkbox" name="" id="id_is_virtual">{% trans 'Online event' %}</label>
    {% bootstrap_field form.type %}
    {% bootstrap_field form.is_aerial %}
    {% bootstrap_field form.main_link %}


    <button class="btn btn-secondary d-block mb-3"data-bs-toggle="collapse" data-bs-target="#additional-urls-collapse" type="button">{% trans 'Additional links' %}</button>
    <div class="collapse" id="additional-urls-collapse">
        {% bootstrap_field form.additional_url_1 %}
        {% bootstrap_field form.additional_label_1 %}
        {% bootstrap_field form.additional_url_2 %}
        {% bootstrap_field form.additional_label_2 %}
    </div>


    <button class="btn btn-primary" type="submit">{% trans 'Add Event' %}</button>
</form>

<!-- Script for the 'online' checkbox -->
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const isVirtualCheckbox = document.querySelector("#id_is_virtual");
        const locationInput = document.querySelector("#id_location");

        function toggleLocationField() {
            if (isVirtualCheckbox.checked) {
                  // Disable the field and set value to 'online'
                locationInput.readOnly = true;
                locationInput.value = "online";
                console.log(locationInput.value);
            } else {
                locationInput.value = "";
                locationInput.readOnly = false;
                console.log(locationInput.value);
            }
        }

        // Add event listener for the checkbox
        isVirtualCheckbox.addEventListener("change", toggleLocationField);

        // Initialize the field state on page load
        toggleLocationField();
    });
</script>
{% endblock content %}

templates/calendar/event_detail.html
{% extends "_base.html" %}

{% block title %}{{ event.name }}{% endblock title %}

{% block content %}

<div class="book-detail">
    <h2><a href="">{{ event.name }}</a></h2>
    <p>Author: {{ event.author }}</p>
    <p>Location: {{ event.location }}</p>
</div>

{% endblock content %}

templates/calendar/event_list.html
{% extends "_base.html" %}

{% block title %}Calendar{% endblock title %}

{% block content %}

<h1>Calendar Page</h1>

{% for event in events %}
    <h2> <a href="{{ event.get_absolute_url }}">{{ event.name }}</a></h2>
    <h3>{{ event.start_date }}</h3> - <h3>{{ event.end_date }}</h3>
    <hr>
{% endfor %}

{% endblock content %}

templates/calendar/event_update.html
{% extends '_base.html' %}
{%load django_bootstrap5 %}
{% load i18n %}



{% block content %}

<form method="post" id="event-update-form">
    {% csrf_token %}
    <h1>{% trans 'Edit event' %}</h1>
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissable fade show d-flex justify-content-between" role="alert" data-bs-dismiss="alert">
        {% bootstrap_form_errors form %}
        <button type="button" class="btn-close ms-2" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% bootstrap_field form.name %}
    <div class="mb-3">
        <label class="form-label" for="id_start_date">Data rozpoczęcia</label>
        <input type="date" name="start_date" value="{{event.start_date|date:'Y-m-d'}}" onfocus="this.showPicker()" class="form-control mb-3" placeholder="Data rozpoczęcia" required="" id="id_start_date">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_end_date">Data zakończenia</label>
        <input type="date" name="end_date" value="{{event.end_date|date:'Y-m-d'}}" onfocus="this.showPicker()" class="form-control" placeholder="Data zakończenia" required="" id="id_end_date">
    </div>
    {% bootstrap_field form.description %}
    {% bootstrap_field form.location %}
    <label><input type="checkbox" name="" id="id_is_virtual">{% trans 'Online event' %}</label>
    {% bootstrap_field form.type %}
    {% bootstrap_field form.is_aerial %}
    {% bootstrap_field form.main_link %}


    <button class="btn btn-secondary d-block mb-3"data-bs-toggle="collapse" data-bs-target="#additional-urls-collapse" type="button">{% trans 'Additional links' %}</button>
    <div class="collapse" id="additional-urls-collapse">
        {% bootstrap_field form.additional_url_1 %}
        {% bootstrap_field form.additional_label_1 %}
        {% bootstrap_field form.additional_url_2 %}
        {% bootstrap_field form.additional_label_2 %}
    </div>


    <button class="btn btn-primary" type="submit">{% trans 'Save changes' %}</button>
</form>

<form action="{% url 'event_delete' event.pk %}" method="post" id="delete-form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" onclick="return confirm('{% trans "Are you sure you want to delete the event?" %}')">{% trans 'Delete event' %}</button>
</form>


{% endblock content %}

templates/calendar/list_layout.html
{% extends '_base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>

{% include 'calendar/navigate_events.html' %}
<div id="list-container">

</div>




<script>
    const yearsData = {{ years|safe }}
    const allEvents = {{ events|safe }}
    const eventTypes = {{ event_types|safe }}
</script>
<script src="{% static 'js/generate_calendar/main_list.js' %}" defer type="module"></script>
{% endblock content %}

templates/calendar/navigate_events copy.html
<div class="calendar-navigation">
    <button class="btn btn-info collapse-filters" type="button" data-bs-toggle="modal" data-bs-target="#collapseFilters">
      Filtruj
    </button>
    <select class="form-select py-1 sticky-dropdown" id="year-dropdown">
      <option selected disabled>Przejdź do roku...</option>
      {% for year in years %}
      <option value="{{ year }}">{{ year }}</option>
      {% endfor %}
    </select>
  </div>


  <!-- filters modal -->
<div class="modal fade" id="collapseFilters" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="filterModalLabel">Filtruj</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p id="type-filter" class="">
            <h5>Typ wydarzenia</h5>
            <input type="checkbox" class="form-check-input mb-2" id="uncheck-all-types" checked>
            <label for="uncheck-all-types">Odznacz/zaznacz wszystkie</label>
            <div id="type-checkboxes">
              {% for type in event_types %}
              <label><input type="checkbox" value="{{ type.1 }}" class="form-check-input type-checkbox" checked> {{ type.1 }}</label>
              {% endfor %}
            </div>
          </p>
          <p id="location-filter">
            <h5>Lokalizacja</h5>
            <select class="form-select" name="" id="location-dropdown">
              <option value="all">Wszystkie</option>
            </select>
          </p>
          <!-- <p id="aerial-filter">
            <label><input type="checkbox" id="only-aerial" class="form-check-input" checked> Tylko związane z aerial</label>
          </p> -->
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Zamknij</button>
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="applyFiltersBtn">Zastosuj</button>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/calendar/navigate_events.html
{% load i18n %}
<div class="calendar-navigation">
    <button class="btn btn-secondary collapse-filters" type="button" data-bs-toggle="modal" data-bs-target="#collapseFilters">
        {% trans "Filter" %}
    </button>
    <select class="form-select sticky-dropdown" id="year-dropdown">
        <option selected disabled>{% trans "Go to year..." %}</option>
        {% for year in years %}
        <option value="{{ year }}">{{ year }}</option>
        {% endfor %}
    </select>
</div>

<!-- Filters Modal -->
<div class="modal fade" id="collapseFilters" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="filterModalLabel">{% trans "Filter" %}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% trans 'Close' %}"></button>
            </div>
            <div class="modal-body">
                <p id="type-filter" class="">
                    <h5>{% trans "Event Type" %}</h5>
                    <input type="checkbox" class="form-check-input mb-2" id="uncheck-all-types" checked>
                    <label for="uncheck-all-types">{% trans "Uncheck/Check all" %}</label>
                    <div id="type-checkboxes">
                        {% for type in event_types %}
                        <label>
                            <input type="checkbox" value="{{ type.0 }}" class="form-check-input type-checkbox" checked> {{ type.1 }}
                        </label>
                        {% endfor %}
                    </div>
                </p>
                <p id="location-filter">
                    <h5>{% trans "Location" %}</h5>
                    <select class="form-select" name="" id="location-dropdown">
                        <option value="all">{% trans "All" %}</option>
                    </select>
                </p>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="applyFiltersBtn">{% trans "Apply" %}</button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/calendar/unverified_events.html
{% extends '_base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<h1>Niezweryfikowane wydarzenia</h1>
{% for event in unverified_events %}
        <div class="event-container d-flex flex-column gap-3 mb-3" id="{{ event.id }}">
            <div>
                <h3 class='d-inline'>{{ event.name }}</h3>
                <span class='{{ event.type }}-type px-1 rounded'>{{ event.type }}</span>
            </div>
            <h5>{{ event.start_date|date:"j-m-Y" }} - {{ event.end_date|date:"j-m-Y" }}</h5>
            <h6><i class="bi bi-pin-map-fill"></i> {{ event.location }}</h6>
            {% if event.description %}
            <div class='modal-description' id='{{ event.id }}-description'>
                {{ event.description }}
            </div>
            {% endif %}
            <div class="modal-links d-flex flex-column gap-2" id="{{ event.id }}-links">
                <div class="modal-main-link">
                    <h4 class="bold">{% trans "Link to the event:" %}</h4>
                    <a href="{{ event.main_link }}" target="_blank" rel="noopener">{{ event.main_link }}</a>
                </div>
                <div class="additional-links d-flex gap-3">
                    {% if event.additional_url_1 %}
                    <a href="{{ event.additional_url_1 }}" target="_blank" rel="noopener">{{ event.additional_label_1 }}</a>
                    {% endif %}
                    {% if event.additional_url_2 %}
                    <a href="{{ event.additional_url_2 }}" target="_blank" rel="noopener">{{ event.additional_label_2 }}</a>
                    {% endif %}
                </div>
            </div>
            <div class="buttons d-flex gap-2">
                <a href="{% url 'event_edit' event.pk %}" class="btn btn-primary">{% trans 'Edit' %}</a>
                <form method="post" action="{% url 'verify_event' event.pk %}">
                    {% csrf_token %}
                    <button class='btn btn-primary' type="submit" onclick="return confirm('{% trans "Are you sure you want to verify the event?" %}')">{% trans "Verify" %}</button>
                </form>
            </div>

        </div>
{% endfor %}


{% endblock content %}

templates/calendar/your_account.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "Your account" %}{% endblock title %}

{% block content %}
<div class="account-changes-container mb-5">
    <h1 class="display-5 text-center mb-3">{% trans "Your account" %}</h1>
    <div class="d-flex gap-3 flex-column flex-sm-row justify-content-center">
        <a class="btn btn-primary" href="{% url 'account_email' %}">{% trans "Change email address" %}</a>
        <a class="btn btn-primary" href="{% url 'account_change_password' %}">{% trans "Change password" %}</a>
        <a class="btn btn-danger d-none" href="#">{% trans "Delete account" %}</a>
    </div>
</div>

<div class="user-events-container">
    <h1 class="display-5 text-center mb-3">{% trans "Manage your events:" %}</h1>
    {% for event in event_list %}
    <div class="d-flex flex-column gap-3 mt-3">
        <div>
            <h3 class='d-inline'>{{ event.name }}</h3>
            <span class='{{ event.type }}-type px-1 rounded'>{{ event.type }}</span>
        </div>
        <h5>{{ event.start_date|date:"j-m-Y" }} - {{ event.end_date|date:"j-m-Y" }}</h5>
        <h6><i class="bi bi-pin-map-fill"></i> {{ event.location }}</h6>
        {% if event.description %}
        <div class='modal-description d-none' id='{{ event.id }}-description'></div>
        {% endif %}
        <div class="modal-links d-flex flex-column gap-2" id="{{ event.id }}-links">
            <div class="modal-main-link">
                <h4 class="bold">{% trans "Link to the event:" %}</h4>
                <a href="{{ event.main_link }}" target="_blank" rel="noopener">{{ event.main_link }}</a>
            </div>
        </div>
        <div class="edit-button-wrapper">
            <a href="{% url 'event_edit' event.pk %}" class="btn btn-primary">{% trans 'Edit' %}</a>
            <hr class="event-hr">
        </div>
    </div>
    {% endfor %}
</div>



{% endblock content %}